### ISSUE TITLE
Errors during compiling

### ISSUE THREAD

**Issue by Miger88** [oberasoftware/jasdb#17]
Hello,

I tried to use jasdb inside an android app. I want to evaluate the performance of jasdb for a study project.
I used the maven dependency to import the librarys.

dependencies {
    ...
    compile group:'com.oberasoftware', name:'jasdb_android', version:'1.1.2'
}

After adding this to my build.gradle I got multiple errors because of duplicate files during build. Therefore I added the following to my build.gradle.
android {
    packagingOptions {
        ...
        pickFirst 'META-INF/spring.tooling'
        pickFirst 'META-INF/spring.handlers'
        pickFirst 'META-INF/spring.schemas'
        pickFirst 'META-INF/services/nl.renarj.jasdb.core.platform.PlatformManager'
        pickFirst 'META-INF/license.txt'
        pickFirst 'META-INF/DEPENDENCIES'
        pickFirst 'META-INF/notice.txt'
        pickFirst 'META-INF/ASL2.0'
    } 
    ...
}

Now I got another error and don't know how to fix it. May be you can help me.
The Error is the following:
Gradle tasks [:app:incrementalDebugSupportDex]
Error:PARSE ERROR:
Error:unsupported class file version 52.0
Error:...while parsing com/oberasoftware/jasdb/api/entitymapper/EntityManager.class
Error:1 error; aborting

Do you have any idea what went wrong?

**Comment by renarj** [comment]
The issue is due to JasDB requiring Java 8 since the 1.1.x line of the product. I am yet to test the Java 8 support in Android (see https://developer.android.com/preview/j8-jack.html).

For the time being i am checking to see how much work it is to provide a Java 7 compatible version of JasDB.

**Comment by Miger88** [comment]
I think java is supported in android. See this article from android developer:
https://developer.android.com/preview/j8-jack.html

**Comment by renarj** [comment]
I have created a small fix for JasDB that allows it to run on the most recent version of Android. This is available for now as JasDB 1.1.3-SNAPSHOT.

In order to use JasDB with Android you do need to use the jack compiler in your gradle project.

So make sure you have something like below with the 'jackOptions' configured and the right java source levels.
```
android {
  ...
  defaultConfig {
    ...
    jackOptions {
      enabled true
    }
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}
```

Due to the large number of dependencies in this build of JasDB you need multi-dex support as described here:
https://developer.android.com/studio/build/multidex.html

Add this compile dependency:
compile 'com.android.support:multidex:1.0.0'

add the ```multiDexEnabled true``` to your defaultConfig section above. 
And last in the app manifest add this line:
```
<application
        ...
        android:name="android.support.multidex.MultiDexApplication">
        ...
    </application>
```

You most likely will need to change the gradle memory settings to be at least 2GB heap ```-Xmx4096m```

**Comment by Miger88** [comment]
Thank you, I will try this tomorrow

**Comment by Miger88** [comment]
What should I write as version in my used dependency?
Before your change I used 
    compile group:'com.oberasoftware', name:'jasdb_android', version:'1.1.2'
as dependency.

**Comment by renarj** [comment]
You can use compile group:'com.oberasoftware', name:'jasdb_android', version:'1.1.3-SNAPSHOT'

**Comment by Miger88** [comment]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.oberasoftware:jasdb_android:1.1.3-SNAPSHOT.
     Searched in the following locations:
         file:/C:/Program Files/Android Studio/gradle/m2repository/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/maven-metadata.xml
         file:/C:/Program Files/Android Studio/gradle/m2repository/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/jasdb_android-1.1.3-SNAPSHOT.pom
         file:/C:/Program Files/Android Studio/gradle/m2repository/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/jasdb_android-1.1.3-SNAPSHOT.jar
         https://jcenter.bintray.com/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/jasdb_android-1.1.3-SNAPSHOT.pom
         https://jcenter.bintray.com/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/jasdb_android-1.1.3-SNAPSHOT.jar
         file:/F:/Android/sdk/extras/android/m2repository/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/maven-metadata.xml
         file:/F:/Android/sdk/extras/android/m2repository/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/jasdb_android-1.1.3-SNAPSHOT.pom
         file:/F:/Android/sdk/extras/android/m2repository/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/jasdb_android-1.1.3-SNAPSHOT.jar
         file:/F:/Android/sdk/extras/google/m2repository/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/maven-metadata.xml
         file:/F:/Android/sdk/extras/google/m2repository/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/jasdb_android-1.1.3-SNAPSHOT.pom
         file:/F:/Android/sdk/extras/google/m2repository/com/oberasoftware/jasdb_android/1.1.3-SNAPSHOT/jasdb_android-1.1.3-SNAPSHOT.jar
     Required by:
         JASDB_DEBUG_APP:app:unspecified

**Comment by renarj** [comment]
Because its a snapshot its not released yet to maven central, so you need to make sure that you have this in gradle file to use the snapshot repository from sonatype:
```
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by Miger88** [comment]
Error:Library reading phase: Type com.google.inject.CreationException from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-no_aop-b10b9c9189ee903679dde521c0f49f4c3b1278bd.jar' has already been imported from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-58a5080fbfafd4ec3ff21b847288d8a57eabb9ec.jar', type 'com.google.inject.CreationException' (see property 'jack.import.type.policy' for type collision policy)

com.android.jack.api.v01.CompilationException: Library reading phase: Type com.google.inject.CreationException from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-no_aop-b10b9c9189ee903679dde521c0f49f4c3b1278bd.jar' has already been imported from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-58a5080fbfafd4ec3ff21b847288d8a57eabb9ec.jar', type 'com.google.inject.CreationException' (see property 'jack.import.type.policy' for type collision policy)

	at com.android.jack.api.v01.impl.Api01ConfigImpl$Api01CompilationTaskImpl.run(Api01ConfigImpl.java:113)
	at com.android.builder.core.AndroidBuilder.convertByteCodeUsingJackApis(AndroidBuilder.java:1931)
	at com.android.build.gradle.tasks.JackTask.doMinification(JackTask.java:148)
	at com.android.build.gradle.tasks.JackTask.access$000(JackTask.java:73)
	at com.android.build.gradle.tasks.JackTask$1.run(JackTask.java:112)
	at com.android.builder.tasks.Job.runTask(Job.java:51)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:223)
	at java.lang.Thread.run(Thread.java:745)
Error:com.android.jack.JackAbortException: Library reading phase: Type com.google.inject.CreationException from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-no_aop-b10b9c9189ee903679dde521c0f49f4c3b1278bd.jar' has already been imported from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-58a5080fbfafd4ec3ff21b847288d8a57eabb9ec.jar', type 'com.google.inject.CreationException' (see property 'jack.import.type.policy' for type collision policy)
	at com.android.jack.Jack.buildSession(Jack.java:1001)
	at com.android.jack.Jack.run(Jack.java:496)
	at com.android.jack.api.v01.impl.Api01ConfigImpl$Api01CompilationTaskImpl.run(Api01ConfigImpl.java:102)
	... 8 more
Error:com.android.jack.library.LibraryReadingException: Library reading phase: Type com.google.inject.CreationException from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-no_aop-b10b9c9189ee903679dde521c0f49f4c3b1278bd.jar' has already been imported from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-58a5080fbfafd4ec3ff21b847288d8a57eabb9ec.jar', type 'com.google.inject.CreationException' (see property 'jack.import.type.policy' for type collision policy)
	at com.android.jack.backend.jayce.JayceFileImporter.doJayceImport(JayceFileImporter.java:138)
	at com.android.jack.Jack.buildSession(Jack.java:997)
	... 10 more
Error:com.android.jack.backend.jayce.TypeImportConflictException: Type com.google.inject.CreationException from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-no_aop-b10b9c9189ee903679dde521c0f49f4c3b1278bd.jar' has already been imported from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-58a5080fbfafd4ec3ff21b847288d8a57eabb9ec.jar', type 'com.google.inject.CreationException' (see property 'jack.import.type.policy' for type collision policy)
	at com.android.jack.backend.jayce.JayceFileImporter.addImportedTypes(JayceFileImporter.java:200)
	at com.android.jack.backend.jayce.JayceFileImporter.doJayceImport(JayceFileImporter.java:133)
	... 11 more
Warning:Exception while processing task java.io.IOException: com.android.jack.api.v01.CompilationException: Library reading phase: Type com.google.inject.CreationException from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-no_aop-b10b9c9189ee903679dde521c0f49f4c3b1278bd.jar' has already been imported from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-58a5080fbfafd4ec3ff21b847288d8a57eabb9ec.jar', type 'com.google.inject.CreationException' (see property 'jack.import.type.policy' for type collision policy)
:app:compileDebugJavaWithJack FAILED
Error:Execution failed for task ':app:compileDebugJavaWithJack'.
> java.io.IOException: com.android.jack.api.v01.CompilationException: Library reading phase: Type com.google.inject.CreationException from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-no_aop-b10b9c9189ee903679dde521c0f49f4c3b1278bd.jar' has already been imported from file 'F:\Android_Studio_Workspace\JASDB\app\build\intermediates\jill\debug\packaged\guice-3.0-58a5080fbfafd4ec3ff21b847288d8a57eabb9ec.jar', type 'com.google.inject.CreationException' (see property 'jack.import.type.policy' for type collision policy)

**Comment by renarj** [comment]
Could you try to use the following dependencies on the gradle module:
```
dependencies {
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:recyclerview-v7:24.2.0'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile(group:'com.oberasoftware', name:'jasdb_android', version:'1.2.0-SNAPSHOT') {
        exclude group: 'org.springframework.boot'
        exclude module: 'guice'
        exclude module: 'logback-classic'
    }
    compile group:'com.google.inject', name:'guice', version:'3.0', classifier: 'no_aop'
}
```

I will update the dependencies on the latest version once we get this working so this will no longer be an issue.

**Comment by Miger88** [comment]
> 

> Error:Failed to resolve: com.oberasoftware:jasdb_android:1.1.3-SNAPSHOT
<a href="openFile:F:/Android_Studio_Workspace/JASDB/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>


My Module Gradle file:

> 

> apply plugin: 'com.android.application'
android {
    packagingOptions {
        /*pickFirst 'LICENSE-EDL-1.0.txt'
        pickFirst 'LICENSE-EPL-1.0.txt'*/
        pickFirst 'META-INF/spring.tooling'
        pickFirst 'META-INF/spring.handlers'
        pickFirst 'META-INF/spring.schemas'
        pickFirst 'META-INF/services/nl.renarj.jasdb.core.platform.PlatformManager'
        pickFirst 'META-INF/license.txt'
        pickFirst 'META-INF/DEPENDENCIES'
        pickFirst 'META-INF/notice.txt'
        pickFirst 'META-INF/ASL2.0'
    }
    compileSdkVersion 24
    buildToolsVersion "24.0.0"
    defaultConfig {
        applicationId "com.example.michael.dbmanager_debug_application"
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        //MAPDB
        jackOptions {
            enabled true
        }
        multiDexEnabled true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
/*dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'com.android.support:multidex:1.0.0'
    compile group:'com.oberasoftware', name:'jasdb_android', version:'1.1.2'
}*/
dependencies {
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:recyclerview-v7:24.2.0'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile(group:'com.oberasoftware', name:'jasdb_android', version:'1.1.3-SNAPSHOT') {
        exclude group: 'org.springframework.boot'
        exclude module: 'guice'
        exclude module: 'logback-classic'
    }
    compile group:'com.google.inject', name:'guice', version:'3.0', classifier: 'no_aop'
}

**Comment by renarj** [comment]
Can you please see if matching this with my below configuration helps? It seems you are missing this part:
```
repositories {
    mavenLocal()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

My full gradle test file for comparison:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

    defaultConfig {
        applicationId "com.oberasoftware.testapplication"
        minSdkVersion 24
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"

        multiDexEnabled true
        jackOptions {
            enabled true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/spring.tooling'
        exclude 'META-INF/spring.handlers'
        exclude 'META-INF/spring.schemas'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/DEPENDENCIES'
    }
}

repositories {
    mavenLocal()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

dependencies {
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:recyclerview-v7:24.2.0'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile(group:'com.oberasoftware', name:'jasdb_android', version:'1.2.0-SNAPSHOT') {
        exclude group: 'org.springframework.boot'
        exclude module: 'guice'
        exclude module: 'logback-classic'
    }
    compile group:'com.google.inject', name:'guice', version:'3.0', classifier: 'no_aop'
}

```

**Comment by Miger88** [comment]
May be it works now.

My Module Gradle File is now the following:
[build.gradle.txt](https://github.com/oberasoftware/jasdb/files/446726/build.gradle.txt)

But Building my project now needs endless time.

last print in Gradle console is: 
:app:compileDebugJavaWithJack    

after that it hangs up as is seems

**Comment by Miger88** [comment]
sry, close was a mistake of my. only want to comment, not close and comment

**Comment by renarj** [comment]
Yeah i also had this hanging build, this is due to the Jack compiler taking a lot of memory. For me what worked was to modify the gradle.properties to increase the memory for gradle using below setting:
```
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```

**Comment by Miger88** [comment]
Very nice, it seems to work now. Thanks for your big help. Very good Support.
