### ISSUE TITLE
Preserving state json metadata

### ISSUE THREAD

**Issue by wendersonferreira** [oberasoftware/jasdb#19]
Hello, how are you?
I have a doubt, I think is potentially one issue, for example

I have the person object, where
Person person = ....
person.setPhones (Arrays.asList ("6275337");

{ "_id": Null, "phones": [ "6275337"]} -> output from ObjectMapper ..
{ "_id": Null, "phones": "6275337"} -> Output from SimpleEntity.toJson () ...

In my view, even if the array has only one value, it should stay as array and not be typed for key, and value.

What do you think? @renarj 

Thanks for your software.

**Comment by wendersonferreira** [comment]
very nice job! Thanks

**Comment by wendersonferreira** [comment]
ObjectMapper objectMapper = new ObjectMapper();

        Person person = new Person();
        person.setName("Person Test");
        person.setPhones(Arrays.asList("12345678"));


        String json = objectMapper.writeValueAsString(person);

        SimpleEntity simpleEntity = SimpleEntity.fromJson(json);
        System.out.println(SimpleEntity.toJson(simpleEntity));


When i use Simple Entity to use the lowest level of your api, i can't preserve state.

SimpleEntity#addValueToProperty

**Comment by wendersonferreira** [comment]
Please, when it's feasible, take a look at what I have in mind, maybe I can help. Thank you.  @renarj 

https://github.com/wendersonferreira/jasdb/commit/9140bad7c5fa1f7ace4a61567ccd4a55626342a7

**Comment by renarj** [comment]
I want to take a bit of a deeper look, however am currently supposed to be on holiday. I will try to take a look in coming days, else it will be next week.

**Comment by renarj** [comment]
I have made a slightly different fix than the proposed fix by extending the api of the SimpleEntity. You can view the PR #30 and check the branch out yourself ISSUE19

If you are ok with these changes i will merge and make this part of the 1.2.0 release i will push out next week.

**Comment by wendersonferreira** [comment]
Sorry for the delay in responding, I ran the code, and it is working perfectly, even without breaking api, excellent solution indeed. Thank you so much. @renarj
