### ISSUE TITLE
JasDB REST via CORS fetch

### ISSUE THREAD

**Issue by MBoegers** [oberasoftware/jasdb#35]
**Situation**
JasDB is running as  standalone, started via start.sh with standard config.
The instance is filled with documents via JavaREST API.
A webapp (within a Browser) reads the Data via REST, not yet.

**Problem**
Because my wabapp is delivered via port 80 and JasDB REST API via port 7050, i have a [CORS ](https://de.wikipedia.org/wiki/Cross-Origin_Resource_Sharing) situation. The Browser rejectes the answer from the JasDB Server because of his [SOP](https://de.wikipedia.org/wiki/Same-Origin-Policy).

Is there a resolution for my situation, beside forking the project?

**Comment by renarj** [comment]
Which version of JasDB are you running, the latest master branch 1.1.2 or 1.2.0?

It could be that the master branch has a CORS issue as significant rewriting happened there. But it should work on 1.1.2 or 1.2, let me know if not else I will investigate

**Comment by MBoegers** [comment]
Hi, 
sorry i was unable to access my source code due to exams...
My JasDB version is **1.1.2-8** according to the log at start up

## Fetching
```shell
curl -i http://localhost:7050/Instances
```
## Result
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 344
Server: Jetty(9.1.2.v20140210)

{
  "instances": [
    {
      "path":"/home/XXX/jasdb/jasdb/DATA/.jasdb",
      "version":"1.1.2-8",
      "instanceId":"default",
      "status":"OK"
    },{
      "path":"./DATA/develop",
      "version":"1.1.2-8",
      "instanceId":"dev",
      "status":"OK"
    },{
      "path":"./DATA/test",
      "version":"1.1.2-8",
      "instanceId":"test",
      "status":"OK"
    }
  ]
}
```

This was also testet with Firefox 55.0.3, Chrome 57.0.2987.98 with the same result, so the browser do not use the response.

## JasDB Configuration
Is the released on with enabled console service.
```
<?xml version="1.0" encoding="UTF-8"?>
<jasdb Version="1.0">
    <Storage>
        <!--<RecordWriter provider="inmemory"/>-->
        <RecordWriter provider="transactional"/>
    </Storage>
    <!-- This allows selecting the mode of flushing data to disk -->
    <flushing mode="interval" enabled="false">
        <Property Name="period" Value="30s"/>
    </flushing>
    <!-- This enables or disables the statistics engine -->
	<Statistics enabled="false"/>
    <Security Enabled="false">
    </Security>
    <!-- Configuration settings for the rest service, like the port number -->
    <Services>
        <Remote service="console" port="7052" Enabled="true">
        </Remote>
        <Remote service="rest" port="7050" oauth="false" Enabled="true">
            <!--<Property Name="sslPort" Value="7051"/>-->
            <!--<Property Name="sslKeystore" Value=""/>-->
            <!--<Property Name="sslKeystorePassword" Value=""/>-->
        </Remote>
    </Services>
    <caching MaxMemory="256m" MemoryMonitorInterval="10s"/>
    <!-- Configuration settings for the btree index -->
	<Index Type="btree" pageSize="512">
		<Caching Enabled="true">
			<Property Name="MaxCacheMemSize" Value="128m"/>
			<Property Name="MaxCachedBlocks" Value="20000"/>
		</Caching>
	</Index>
</jasdb>
```

**Comment by renarj** [comment]
I have found the issue, seems a Jersey upgrade in latest release caused this, have resolved it by manually adding the origins header. Needs a permanent fix on Master branch, will release a hotfix branch tonight.

**Comment by MBoegers** [comment]
Cheers!

**Comment by renarj** [comment]
Release 1.2.1 is available and can be used. Please make sure to use the 1.2.1 maven artefacts or the latest release zip file available on the releases page on github
